### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [pyocd/pyOCD#1007]
The markup version of the readme that is displayed for the main page in this repo contains the following link:

“GNU Arm Embedded”
Status code [404:NotFound] - Link: https://developer.arm.com/tools-and-software/open-source-software/gnu-toolchain/gnu-rm

--

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).

To re-check this Repo use this link: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fpyocd%2fpyOCD
To check all Repos for this GitHub account use this link: http://githubreadmechecker.com/Home/Search?User=pyocd

If this has been in any way helpful then please consider giving the above Repo a Star.
If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by flit** [comment]
Thanks for reporting the issue. Just starred your tool, I'm sure I'll be using it in the future! 🥇
