### ISSUE TITLE
Enhancement Request: Publish SWO/SWV stream to TCP port

### ISSUE THREAD

**Issue by mubes** [pyocd/pyOCD#1009]
Hi,

For a CMSIS-DAP v2 interface, would it be possible to publish the SWO output (the second USB IN stream) to a TCP port? That would allow utilities such as Orbuculum to connect directly to it (indeed, if it was on port 3443 it would be transparent and wouldn't even need any command line options). I think OpenOCD is supporting this in development builds now.

Regards
DAVE

**Comment by flit** [comment]
Definitely would be nice to have this. I can't really provide an estimate as to when it will be implemented; there are many other tasks on the table. (Any help would be appreciated.)

Thanks for the info about port 3443, I wasn't aware that was Orbuculum's default port.

**Comment by mubes** [comment]
Hi Chris,

I'm the author of Orbuculum and will happily do some reasonably thorough 
testing with it once you've got it in pyocd. I'd do it myself but my 
Py-foo is weak and it would just get added to the 1001 other things I'm 
not doing... If you use 3443 then pyocd will plug directly into the 
various orb clients and orbuculum itself (which is the multiplexer) can 
be bypassed; Having access to orbtop alone makes it definitely worth the 
effort of adding the functionality.

Regards

DAVE

**Comment by flit** [comment]
🤣 Nice to meet you! And I totally understand you about the 1001 other things…
