### ISSUE TITLE
Does pyocd support cortex_a processors?

### ISSUE THREAD

**Issue by hunterafish** [pyocd/pyOCD#1029]
Does pyocd support cortex_a processors? 

I found no code about cortex_a.

Thanks.

**Comment by flit** [comment]
Not yet, sorry! It's on the list of future features, though. Any contributions towards that goal would, of course, be greatly appreciated. 😄

**Comment by cederom** [comment]
I can see that Renesas R7S7 MCU which is Cortex-A9 from GR-PEACH [1] can be installed to pyOCD with CMSIS Pack Manager. This board is also supported by DAPLink.

What features can be provided by CPM by the way? :-)

[1] https://os.mbed.com/platforms/Renesas-GR-PEACH/

**Comment by hunterafish** [comment]
I got it. Thanks for quick responding!
