### ISSUE TITLE
AttributeError 'Logger' object has no attribute 'warining'

### ISSUE THREAD

**Issue by r8d8** [pyocd/pyOCD#1058]
https://github.com/pyocd/pyOCD/blob/91b68e4aa6ef78aa1b547b51314621ad6bd59ece/pyocd/gdbserver/context_facade.py#L153

**Comment by flit** [comment]
Ouch, that's embarrassing!

**Comment by flit** [comment]
How did you encounter this bug? The warning should only be printed when, as it says, gdb attempted to set the value of an invalid CPU register.

**Comment by r8d8** [comment]
I was connecting to microbit (version 2), and error appeared during ‘load’
command

**Comment by flit** [comment]
Ok, thanks!
