### ISSUE TITLE
CY8CKIT-059 PSoC 5LP - not detected 

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [pyocd/pyOCD#1225]
I have one of [these](https://www.cypress.com/documentation/development-kitsboards/cy8ckit-059-psoc-5lp-prototyping-kit-onboard-programmer-and).

it shows up in `lsusb`:

```
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 003: ID 258a:1007 SINOWEALTH Game Mouse
Bus 005 Device 002: ID 04b3:3025 IBM Corp. NetVista Full Width Keyboard
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0025 Intel Corp. Wireless-AC 9260 Bluetooth Adapter
Bus 001 Device 002: ID 1b1c:0a67 Corsair CORSAIR VIRTUOSO Wireless Gaming Headset
Bus 001 Device 004: ID 04b4:f139 Cypress Semiconductor Corp. Cypress KitProg
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

there was no udev rule built in to pyocd for it, so I wrote my own:

```
tether@Nervous-Carrier ~> grep f139 /etc/udev/rules.d/*
/etc/udev/rules.d/CY8CKIT-059.rules:SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", ATTR{idProduct}=="f139", MODE:="666"
```

No way of verifying this works, of course.

README.md claims pyOCD supports KitProg. So it ought to work.

`pyocd list` still doesn't show it.

please advise.

**Comment by flit** [comment]
(Apologies for being slow to reply!)

(TL;DR) PyOCD supports KitProg2 and KitProg3, this board has KitProg.

PyOCD supports the more recent CMSIS-DAP compatible variants of KitProg. That is KitProg2 in CMSIS-DAP mode, and KitProg3 which is always CMSIS-DAP v2 (afaik). (For KitProg2, you have hold down a button to put it in CMSIS-DAP mode, also called Mass Storage Programmer mode; see the KitProg2 user guide for details.)

It looks like the CY8CKIT-059 has KitProg (v1, I guess). This KitProg version does not support a CMSIS-DAP mode. I just checked the user guide, and while there is a section about a Mass Storage Programmer mode there is nothing that mentions CMSIS-DAP.

Please also note that pyocd doesn't really support PSoC 5LP devices.  Support has been requested from Cypress (for PSoC 4 devices too) by several users but they have so far declined. Also, there is not a CMSIS-Pack for these devices that I'm aware of. You may be able to connect pyocd to the 5LP but would not be able to program flash (and I'm not even sure about connecting; PSoC devices generally have complex, custom debug logic for connecting).

cc @bohdan-tymkiv @Cypress-OpenOCD
