### ISSUE TITLE
pyyaml version conflict during installation

### ISSUE THREAD

**Issue by maciejbocianski** [pyocd/pyOCD#1232]
After latest cmsis-pack-manager update from 0.3.0 to 0.4.0 we get python module conflict during pyocd installation 
```
ERROR: cmsis-pack-manager 0.4.0 has requirement pyyaml<7.0,>=6.0, but you'll have pyyaml 5.4.1 which is incompatible.
```

cmsis-pack-manager 0.4.0 requires  pyyaml<7.0,>=6.0
but pyocd still requires pyyaml>=5.1,<6.0

**Comment by flit** [comment]
Should be fixed in [v0.32.1](https://github.com/pyocd/pyOCD/releases/tag/v0.32.1).
