### ISSUE TITLE
Slack invitation has expired

### ISSUE THREAD

**Issue by FoundationKen** [pyocd/pyOCD#1254]
I'd like to join the Slack channel, but the invitation link has expired.

Cheers!

**Comment by mbrossard** [comment]
It seems invitation links are only valid for 30 days. You should be able to use [this one](https://join.slack.com/t/pyocd/shared_invite/zt-zqjv6zr5-ZfGAXl_mFCGGmFlB_8riHA). It would be nice to have a solution that lasts longer.

**Comment by flit** [comment]
Thanks for letting us know! I updated the link with one that is _supposed_ to be non-expiring.
