### ISSUE TITLE
Replace naturalsort dependency with natsort or remove altogether

### ISSUE THREAD

**Issue by dvzrv** [pyocd/pyOCD#1317]
Hi! I'm about to package this project for Arch Linux (due to other dependencies).

Unfortunately the [naturalsort](https://github.com/xolox/python-naturalsort) upstream seems very dead, [does conflict with natsort](https://github.com/xolox/python-naturalsort/issues/4) (which is actively maintained and already packaged on Arch Linux), has less features and thus seems less fit for being included in any upstream project.
It would be very cool if you could switch to using natsort, or remove the necessity of naturalsort altogether, which seems to be only required for this command:
https://github.com/pyocd/pyOCD/blob/7d164d99e816c4ef6c99f257014543188a0ca5a6/pyocd/commands/commands.py#L119-L120

**Comment by flit** [comment]
I'm pretty sure I used naturalsort because it supports Python 2, which was needed for pyocd at the time. But now that pyocd is Python 3-only it's nice to be able to update. 😄
