### ISSUE TITLE
Consider replacing elapsedtimer with Python builtins

### ISSUE THREAD

**Issue by dvzrv** [pyocd/pyOCD#1333]
As this project only supports python >= 3.6 (at this point) it can be considered to remove the test dependency on elapsedtimer.

https://github.com/pyocd/pyOCD/blob/6a6fa2834d3aed120125bbef04e69f9f6118dda2/test/unit/test_semihosting.py#L74-L94

Instead [timeit](https://docs.python.org/3.10/library/timeit.html) may be used which relies on [time.perf_counter()](https://docs.python.org/3.10/library/time.html#time.perf_counter) -  the timer with the highest resolution - by default.

The above code in the test setup could be replaced, removing a test dependency (at the cost of reimplementing/ redesigning some of its features e.g. as a fixture).

**Comment by flit** [comment]
Thanks for pointing this out. This particular case should actually be replaced with pyocd's `Timeout` class.
