### ISSUE TITLE
GenericMemAPTarget wrong inheritance

### ISSUE THREAD

**Issue by ihos-cypress** [pyocd/pyOCD#1345]
Class `GenericMemAPTarget` (module pyocd/coresight/generic_mem_ap.py) inherited from the `CoreSightComponent` class. However `DebugContext` (module pyocd/debug/context.py) constructor checks whether `isinstance(self._parent, CoreSightCoreComponent)`. This causes the error `'SYS_AP_PSoC64' object has no attribute 'core'` when try to open a session. In version 0.32.3, the `GenericMemAPTarget` class is inherited from `CoreSightCoreComponent`.

Code to reproduce:
```
from pyocd.core.helpers import ConnectHelper

session = ConnectHelper.session_with_chosen_probe(
    blocking=False,
    options={'target_override': 'cy8c64_sysap'}
)
if session is not None:
    session.open()
```

**Comment by flit** [comment]
@ihos-cypress Fyi, this should be fixed in #1350. If you have a chance to test, I would appreciate.

(Though, um, I can obviously understand if you can't. Please accept my sincerest wish that you, your family, friends, and colleagues have found refuge and safety. 🙏🏽 )
