### ISSUE TITLE
 [question] How to download a binary file to external flash

### ISSUE THREAD

**Issue by xray-bit** [pyocd/pyOCD#1356]
I have used [pyOCD/FlashAlgo](https://github.com/pyocd/FlashAlgo) to generate an FLM file for external flash. How to download a binary file to external flash using CLI or API? I've searched on docs, issues and google, but couldn't find any relevant questions.

**Comment by xray-bit** [comment]
After I cloned pyOCD, I added a new target referring to the [docs/adding_new_targets.md](https://github.com/pyocd/pyOCD/blob/main/docs/adding_new_targets.md) documentation. External flash can now be programmed using the CLI. 
Now my question is, after opening a `session` using API, is it possible to use one algorithm to program the internal flash and then switch to another algorithm to program the external flash?

**Comment by xray-bit** [comment]
[docs/user_scripts.md](https://github.com/pyocd/pyOCD/blob/main/docs/user_scripts.md)

**Comment by xray-bit** [comment]
[docs/user_scripts.md](https://github.com/pyocd/pyOCD/blob/main/docs/user_scripts.md)

**Comment by elfmimi** [comment]
Maybe link to pyocd.io is better for sharing.
https://pyocd.io/docs/user_scripts.html
