### ISSUE TITLE
RTT: control block not found

### ISSUE THREAD

**Issue by flit** [pyocd/pyOCD#1471]
Reports of RTT control block not being found.

@purpl3F0x (Zephyr based firmware):
![](https://user-images.githubusercontent.com/16735391/196469357-eced2ce7-ff18-4c45-9bf7-56ad855c8941.png)

@letshin:
![](https://user-images.githubusercontent.com/40326519/200945472-0db8be52-b0fd-4fa5-b275-c47a08a752b8.png)

These may or may not be the same issues.

Originally reported at end of #1241.

**Comment by flit** [comment]
@letshin @purpl3F0x Do either of you have example firmware you could attach to this issue?  I can try building a Zephyr app, but it'd be nice to be able to exactly reproduce your issues. Thanks.

**Comment by letshin** [comment]
Hi. I'd preface this by saying that I know very little about working with OCD. 

I've been trying to build the b-parasite firmware:
https://github.com/rbaron/b-parasite/tree/main/code/b-parasite

I've attached the hex file I used here (I assume you meant this by firmware?)
[nrf52840_xxaa.hex.txt](https://github.com/pyocd/pyOCD/files/9975438/nrf52840_xxaa.hex.txt)

**Comment by letshin** [comment]
I initially attached the firmware here but actually writing out a response here made me realise that I had compiled for the wrong chip version (RF52840 vs NRF52833). Compiling the correct firmware and loading it resolved this issue (see screenshot below). Apologies for the mix-up on my end - this is my first experience with dealing with OCD stuff.

![image](https://user-images.githubusercontent.com/40326519/200952730-e18d67f1-bf50-4e23-9855-7ce173611752.png)

**Comment by flit** [comment]
@letshin No worries, I'm just glad it ended up working for you! 😄 

(I'll keep this issue open for a little while in case @purpl3F0x replies.)

**Comment by purpl3F0x** [comment]
if you could give me few days, im busy this weekend.
also if @letshin wants' to upload its hex for cross reference just in case I'm compiling something wrong :P

**Comment by letshin** [comment]
Firmware that didn't work (probably this, it was in my documents folder, didn't bother recompiling).

[nrf52840_xxaa.hex.txt](https://github.com/pyocd/pyOCD/files/9998844/nrf52840_xxaa.hex.txt)

Version that works:
[nrf52833_xxaa.hex.txt](https://github.com/pyocd/pyOCD/files/9998851/nrf52833_xxaa.hex.txt)

**Comment by purpl3F0x** [comment]
Hello, sorry for the extra long delay. logging to rtt is working!
You can close this issue
