### ISSUE TITLE
Using pyinstaller to build executable but cannot load plugins

### ISSUE THREAD

**Issue by randychung75** [pyocd/pyOCD#1472]
Hello,

I want to create a daplink loader using pyocd, but when I use pyinstaller to pack it, it seems cannot load plugins (pyocd/probe/aggregator.py line 83 **_load_plugin_classes_of_type('pyocd.probe', PROBE_CLASSES, DebugProbe)_**), so executing the .exe file cannot link to any probe, but it is working on IDE mode.

Error message:
OSError: cannot load library 'C:\Users\***\AppData\Local\Temp\_MEI53162\cmsis_pack_manager\_native__lib.cp39-win_amd64.pyd': error 0x7e

Does anyone know how to fix this issue?

Thanks.

Regards
Randy

**Comment by elfmimi** [comment]
Here are some hints.
https://github.com/pyocd/pyOCD/discussions/1274

**Comment by randychung75** [comment]
This hint is worked!
Thanks for your help!

**Comment by USTHzhanglu** [comment]
I also encountered similar problems，and finally i add this in .spec
```
datas=[('./venv/Lib/site-packages/libusb_package/libusb-1.0.dll', '.'),('./venv/Lib/site-packages/cmsis_pack_manager/cmsis_pack_manager/native.so','./cmsis_pack_manager/cmsis_pack_manager/.')],
```
