### ISSUE TITLE
pyOCD Does Not Support STM32F407VGT6 Board

### ISSUE THREAD

**Issue by XiaZhouZero** [pyocd/pyOCD#1498]
I was using pyOCD to set up gdb server for my `STM32F407VGT6` board. Although pyOCD supports this board as indicated in the [board/board_ids.py](https://github.com/pyocd/pyOCD/blob/447416d2060d1ccbff670b984b9237c8c61b52ef/pyocd/board/board_ids.py#L174), it failed anyway.
```
 $ pyocd list
  #   Probe/Board    Unique ID                  Target
-----------------------------------------------------------------
  0   STM32 STLink   066DFF565257867767181439   ✖︎ stm32f407vgtx
      DISCO-F407VG

 $ pyocd json
{
    "pyocd_version": "0.34.3",
    "version": {
        "major": 1,
        "minor": 1
    },
    "status": 0,
    "boards": [
        {
            "unique_id": "066DFF565257867767181439",
            "info": "DISCO-F407VG",
            "board_vendor": null,
            "board_name": "DISCO-F407VG",
            "target": "stm32f407vgtx",
            "vendor_name": "STMicroelectronics",
            "product_name": "STM32 STLink"
        }
    ]
}

 $ pyocd gdbserver
0000711 C Target type stm32f407vgtx not recognized. Use 'pyocd list --targets' to see currently available target types. See <https://pyocd.io/docs/target_support.html> for how to install additional target support. [__main__]
```
It seems that my the board ID of my STM32F047 board does not match to the dictionary in [board/board_ids.py](https://github.com/pyocd/pyOCD/blob/447416d2060d1ccbff670b984b9237c8c61b52ef/pyocd/board/board_ids.py#L174).
Should I add a new item into this dictionary? H ow to get the correct board ID of my STM32F047 board? Can anyone help me out? 
Thanks in advance!

**Comment by XiaZhouZero** [comment]
And how to get the correct board ID of my STM32F047 board?

**Comment by mathias-arm** [comment]
The message says `stm32f407vgtx` target is not installed, I don't think the Board ID is an issue. The document in the message (https://pyocd.io/docs/target_support.html) details the process to fix the missing target.

It should be something like:
```
$ pyocd pack -u
$ pyocd pack -i stm32f407vgtx
```

**Comment by flit** [comment]
It looks to me like everything worked, or would have.

The errors when running `pyocd pack update` are expected, because several pack vendors have issues with their servers. There is nothing we can do except report the errors. (However, the error messages need to be much more clear!)

Downloading STM32 packs takes quite a while because the packs are rather large. Due to current limitations in the Python interface to the Rust based backend for downloading packs, it's not possible to report download progress.

**Comment by XiaZhouZero** [comment]
I see. Thanks for your reply @flit !
