### ISSUE TITLE
pyocd should support pylink-square v1.0

### ISSUE THREAD

**Issue by LockeKK** [pyocd/pyOCD#1516]
I just updated my pylink-square to the latest v1.0. pyocd has a dependency on pylink-square.

pyocd 0.34.3 requires pylink-square<1.0,>=0.11.1, but you have pylink-square 1.0.0 which is incompatible.

Please update pyocd dependency requirement.

**Comment by flit** [comment]
I can try to get it in before the next release. Could you submit a PR to update this?

**Comment by flit** [comment]
Sorry, I'm a dumbass and forgot there's already a PR #1503 to require pylink-square 1.x.
