### ISSUE TITLE
Bugs in API examples

### ISSUE THREAD

**Issue by rgrr** [pyocd/pyOCD#1525]
Concerning the API examples found in https://github.com/pyocd/pyOCD/blob/main/docs/api_examples.md following remarks/questions:

- hello world: after target.resume() my setup cannot access the core registers.  I have to do a target.halt().  Is it just me?
- breakpoint: the assert fails because address read from ELF has LSB set (thumb) so TMO the assert should read "assert pc == addr & ~0x01".  Again: just me?
- breakpoint: "target.remove_breakpoint()" wants an address

My setup is an nRF52840, compiler latest+ llvm.

Ok, to create some more examples (and correct the old ones) and make a PR?

**Comment by flit** [comment]
It's not just you. 😞 And yes, a PR would be awesome! 😄
