### ISSUE TITLE
How to change option bytes for stm32l072 series chip

### ISSUE THREAD

**Issue by zhangxj-1** [pyocd/pyOCD#1526]
Now I need to change the read out protection of stm32l072 series chip, I tried to write 0x1ff80000, but it failed.
So is there any other ways to realize this function with PyOCD?

**Comment by flit** [comment]
The easiest way is to build a binary file that contains the OPT values, then use `pyocd load` to write it to the OPT memory address. Same for EEPROM.

Example:
```
pyocd load optdata.bin@0x1ff80000
```

(Hex and ELF files can be used too, and wouldn't need the address explicitly declared here since they include target addresses.)
