### ISSUE TITLE
Archlinux will encounter the following error when executing pyocd

### ISSUE THREAD

**Issue by zhkag** [pyocd/pyOCD#1647]
Fatal glibc error: malloc.c:2594 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)

**Comment by dsa-lab815** [comment]
Hello, I have this problem on Debian 12 and on Ubuntu 22.04.  I don't see the commit that fixes it on main or develop branches.  Please advise.
