### ISSUE TITLE
Pyocd + CMSIS-DAP bulk mode.

### ISSUE THREAD

**Issue by fabio-ric-silva** [pyocd/pyOCD#1744]
Hi there, how is it doing? Hope you're doing great!

Dears;

I have been doing some tests to speed up the CMSIS-DAP utilizing the interface with lpc11u35.

Any test I did had no many interesting results, until I tested it with bulk mode.

I have made the changes for working in drag and drop mode, utilizing bulk instead of HID, and what before was taken about 25 seconds, now takes about 7 seconds!

The problem!

After changing the USB transfer mode from HID to bulk, the CMSIS-DAP interface is not being recognized neither by Keil nor Pyocd!

Question!

There is any way of adjusting the pyocd for working with HID and bulk, or just bulk whatever?

Sincerely;

**Comment by mathias-arm** [comment]
This looks like a problem with your changes (I assume based https://github.com/ARMmbed/DAPLink/issues/1085) in DAPLink, not an issue in PyOCD. I will move the conversation to the DAPLink issue.
