### ISSUE TITLE
About pyocd updating.

### ISSUE THREAD

**Issue by lennvn** [pyocd/pyOCD#1746]
May I ask is there anybody else handling the pull requests? And which branch should the PR merged into, main or develop?

**Comment by mathias-arm** [comment]
The branch depends on the content of the PR. See https://github.com/pyocd/pyOCD/blob/main/docs/developers_guide.md#branch-configuration-policy

**Comment by lennvn** [comment]
Thanks @mathias-arm
There's one more question, how to solve this problem on branch 'develop'?
![image](https://github.com/user-attachments/assets/d1d5a9c6-3484-4169-a2c8-d6014f14f0e5)

**Comment by mathias-arm** [comment]
Without the link to the PR or GitHub Actions run, it's impossible to help.

**Comment by lennvn** [comment]
Here is my PR link. 
https://github.com/pyocd/pyOCD/pull/1747
Thanks.

**Comment by mathias-arm** [comment]
I think `develop` is missing this change https://github.com/pyocd/pyOCD/commit/5166025ae5da5e093d6cfe2b26cae5e1334476e4

**Comment by lennvn** [comment]
Thank you so much@mathias-arm. The problem seems to have been solved.
