### ISSUE TITLE
pyocd pack -u error trying to connect

### ISSUE THREAD

**Issue by xia-rj** [pyocd/pyOCD#923]
I want to using pack -u update cmsis_pack, but there have an erro. When I used curl, I find that this page has moved https://sadevicepacksprodus.blob.core.windows.net/idxfile/index.pidx. How to fix the problem.

**Comment by boraozgen** [comment]
Same

`Aug 06 11:32:59.769 ERRO https://www.keil.com/pack/index.pidx: error trying to connect: unexpected end of file, uri: http://www.keil.com/pack/index.pidx`

**Comment by flit** [comment]
Thanks for letting me know—I wasn't aware of this. This issue will have to be worked around on the server.

**Comment by flit** [comment]
The server should be fixed. Can you please test and confirm?

(Note that there are known issues downloading the STM32 F7xx, L0xx, and G4xx pack descriptors. These failures are being looked at.)

**Comment by tarj** [comment]
Tried pyocd pack -u
0001896:INFO:__main__:Updating pack index...
Aug 10 20:04:57.840 ERRO download of "http://www.keil.com/pack/ARM.minar.pdsc" failed: unexpected end of file
Aug 10 20:04:57.846 ERRO download of "http://www.keil.com/pack/Keil.Kinetis_K60_DFP.pdsc" failed: unexpected end of file
...
Aug 10 20:08:07.274 WARN tried to parse element "package" from element "html"
Aug 10 20:08:07.281 WARN tried to parse element "package" from element "html"
Aug 10 20:08:07.342 WARN error while parsing attribute at position 26: Got 2 '=' tokens
...
Complete log:
[pyocd_pack_update.log](https://github.com/mbedmicro/pyOCD/files/5052731/pyocd_pack_update.log)

**Comment by flit** [comment]
Thanks for testing and the log. I'll keep working on it.

**Comment by flit** [comment]
What's really strange is that only a handful of STM32 packs fail for me. I also don't see the Maxim failures. (The Qorvo failures are known; there's nothing we can do about it.)

**Comment by tarj** [comment]
I don't know if is it matter, but I reinstalled pyocd==0.27.1.dev45 (from source - setup.py install) and ran it again:
pyocd pack -u
0001673:INFO:__main__:Updating pack index...
Aug 11 09:28:34.188 ERRO expecting </meta> found </HEAD>, uri: http://www.keil.com/pack/index.pidx

**Comment by flit** [comment]
Ok, it _should_ be fixed completely now. Please retest and confirm. (Really sorry for the trouble!)

**Comment by flit** [comment]
@tarj I think you might have happened to test just as the server was being modified, which could account for seeing the failure again.

**Comment by flit** [comment]
Closing. Everything is working now. If this pops up again please reopen.

**Comment by frmdstryr** [comment]
Just hit this while trying to setup a new system today:

```
(base) user@hp:~$ pyocd pack -u
0000647:INFO:__main__:Updating pack index...
Oct 08 19:32:49.077 ERRO https://www.keil.com/pack/index.pidx: error trying to connect: unexpected end of file, uri: http://www.keil.com/pack/index.pidx
Could not open file "/home/user/.local/share/cmsis-pack-manager/aliases.json"
```

**Comment by flit** [comment]
@frmdstryr Thanks for reporting. I see that now too. Something changed on the keil.com server. I've raised it internally so hopefully it will be fixed soon.

As a temporary workaround you can follow the instructions regarding [manual pack usage](https://github.com/pyocd/pyOCD/blob/master/docs/target_support.md#manual-pack-usage) from the pyocd target support docs.

**Comment by flit** [comment]
Fixed (again).
